services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
